
package com.mycompany.prj_jogardado;

/*
    ANA BEATRIZ MARTINS BATISTA
    BRUNO SANTOS PROTUGAL
    MARIANE BATISTA DE SOUZA
*/
public class JogoDadosGUI extends javax.swing.JFrame {

    /**
     * Creates new form JogoDadosGUI
     */
    public JogoDadosGUI() {
        initComponents();
    }
    
    ControladorJogoDados controlador = new ControladorJogoDados();


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Fundo = new javax.swing.JPanel();
        txt_jogador = new javax.swing.JTextField();
        btn_disputar = new javax.swing.JButton();
        lbl_resultado = new javax.swing.JLabel();
        lbl_imgfundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogo de Dados - Engenharia de Software");
        setResizable(false);

        Panel_Fundo.setToolTipText("");
        Panel_Fundo.setMaximumSize(new java.awt.Dimension(500, 500));
        Panel_Fundo.setMinimumSize(new java.awt.Dimension(500, 500));
        Panel_Fundo.setLayout(null);

        txt_jogador.setBackground(new java.awt.Color(70, 42, 90));
        txt_jogador.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        txt_jogador.setForeground(new java.awt.Color(255, 255, 255));
        txt_jogador.setToolTipText("");
        txt_jogador.setBorder(null);
        txt_jogador.setOpaque(false);
        txt_jogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jogadorActionPerformed(evt);
            }
        });
        Panel_Fundo.add(txt_jogador);
        txt_jogador.setBounds(60, 140, 310, 40);

        btn_disputar.setBorderPainted(false);
        btn_disputar.setContentAreaFilled(false);
        btn_disputar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_disputarActionPerformed(evt);
            }
        });
        Panel_Fundo.add(btn_disputar);
        btn_disputar.setBounds(40, 200, 120, 50);

        lbl_resultado.setBackground(new java.awt.Color(255, 255, 255));
        lbl_resultado.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_resultado.setForeground(new java.awt.Color(255, 255, 255));
        lbl_resultado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Panel_Fundo.add(lbl_resultado);
        lbl_resultado.setBounds(80, 350, 210, 90);

        lbl_imgfundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/prj_jogardado/img de fundo.jpg"))); // NOI18N
        Panel_Fundo.add(lbl_imgfundo);
        lbl_imgfundo.setBounds(0, 0, 500, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_disputarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_disputarActionPerformed
                String nomeJogador = txt_jogador.getText();
                if (nomeJogador.equals("")) {
                    lbl_resultado.setText("Insira o seu nome!");                                              
                }
                else{
                controlador.adicionarJogador(nomeJogador);
                String resultado = controlador.jogarRodada(nomeJogador);
                lbl_resultado.setText(resultado);
                }
    }//GEN-LAST:event_btn_disputarActionPerformed

    private void txt_jogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jogadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jogadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogoDadosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogoDadosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogoDadosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogoDadosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogoDadosGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_Fundo;
    private javax.swing.JButton btn_disputar;
    private javax.swing.JLabel lbl_imgfundo;
    private javax.swing.JLabel lbl_resultado;
    private javax.swing.JTextField txt_jogador;
    // End of variables declaration//GEN-END:variables
}
